### ISSUE TITLE
loginResult missing first name, last name, avatar.

### ISSUE THREAD

**Issue by alpamys-qanybet** [doomsower/react-native-vkontakte-login#36]
Hi there,
I need to authorize through your module and want to retrieve first name, last name and avatar within loginResult.

**Comment by doomsower** [comment]
Hi! This is impossible, because wrapped android sdk doesn't return this information. You have to make API request after you've obtained access token.

**Comment by doomsower** [comment]
Unlike iOS, android [AccessToken](https://github.com/VKCOM/vk-android-sdk/blob/3680996ac3709daa816a4d784e090b1a4f184e27/vksdk_library/src/main/java/com/vk/sdk/VKAccessToken.java) doesn't contain user profile.

Regarding Odnoklassniki. I wrote wrapper long time ago, but never tested it and it's outdated now. This happened because requirements changed and I never needed ok auth since then. You can find it somewhere on my profile. Creating bridge is not that difficult even when you don't know native language. There are couple of modules that can scaffold bridge module for you, I recommend to find and use one.

**Comment by stereodenis** [comment]
@doomsower is it possible to add these fields?

**Comment by doomsower** [comment]
@stereodenis if android now returns them, then I can accept PR
